-- ─────────────────────────────────────────────────────────────────────
-- seed.sql
-- Seed the control library v0.1.0 for development. Run via:
--   supabase db reset  (in dev) or
--   psql -f seed.sql
-- ─────────────────────────────────────────────────────────────────────

-- The control library seed is generated by `pnpm seed:controls` from
-- packages/control-library. This file just inserts the meta row and a
-- couple of demo tenants / users for local development.

insert into public.control_libraries (version, published_at, published_by, change_log, control_count, is_current)
values (
  '0.1.0',
  '2026-08-11T00:00:00Z',
  'Axiom Minds · Founder',
  'Initial v0.1.0: 46 controls across 13 domains.',
  46,
  true
)
on conflict (version) do nothing;

-- A demo founder user (no auth — must be created via Supabase Auth signup
-- in dev; this is just a placeholder row that the auth.users FK can resolve
-- to after the first sign-in).
-- In dev, run:
--   1. Sign up the founder via the Supabase dashboard / API
--   2. Then run:
--      update public.users set is_axiom_internal = true where email = 'founder@axiomminds.ai';

-- A demo tenant for local exploration
insert into public.tenants (id, slug, name, tier)
values (
  '00000000-0000-0000-0000-000000000001',
  'demo-client',
  'Demo Client (Acme Fintech Pvt Ltd)',
  'growth'
)
on conflict (id) do nothing;

-- A demo founder user for dev / e2e exploration
insert into auth.users (id, instance_id, aud, role, email, encrypted_password, email_confirmed_at, created_at, updated_at, raw_app_meta_data, raw_user_meta_data, is_super_admin)
values (
  '00000000-0000-0000-0000-000000000001',
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  'founder@axiomminds.ai',
  crypt('Admin@12345678', gen_salt('bf')),
  now(),
  now(),
  now(),
  '{"provider":"email","providers":["email"]}',
  '{"full_name":"Founder"}',
  false
)
on conflict (id) do nothing;

insert into public.users (id, email, full_name, is_axiom_internal)
values (
  '00000000-0000-0000-0000-000000000001',
  'founder@axiomminds.ai',
  'Founder',
  true
)
on conflict (id) do nothing;

insert into public.tenant_users (tenant_id, user_id, role)
values (
  '00000000-0000-0000-0000-000000000001',
  '00000000-0000-0000-0000-000000000001',
  'owner'
)
on conflict (tenant_id, user_id) do nothing;

-- Public gap-scan submissions are stored without a tenant; the control
-- library is the only data that lives outside tenant isolation at the
-- schema level.
