import Link from 'next/link';
import { createSupabaseServerClient, createSupabaseAdmin } from '@axiom/supabase';
import { BRAND } from '@axiom/config';
import {
  PageHeader,
  Stat,
  StatGrid,
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  Badge,
  AgentPill,
  StatusBadge,
} from '@axiom/ui';
import { redirect } from 'next/navigation';

export const dynamic = 'force-dynamic';

export default async function WorkbenchPage() {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect('/login');

  // The workbench is an Axiom-internal surface. Check this through the
  // user-scoped client before using the service-role client for cross-tenant
  // aggregates. A login alone must never grant cross-tenant visibility.
  const { data: profile, error: profileError } = await supabase
    .from('users')
    .select('is_axiom_internal')
    .eq('id', user.id)
    .maybeSingle();
  if (profileError || !profile?.is_axiom_internal) redirect('/portal');

  const admin = createSupabaseAdmin();

  const [tenantsRes, engagementsRes, plansRes, ledgerRes, breachRes, dsarRes] = await Promise.all([
    admin.from('tenants').select('id, name, tier, is_sdf', { count: 'exact' }).limit(5),
    admin
      .from('engagements')
      .select('id, title, status, posture_score, started_at, tenant_id', { count: 'exact' })
      .order('started_at', { ascending: false })
      .limit(8),
    admin
      .from('remediation_plans')
      .select('id, title, status, tenant_id, created_at', { count: 'exact' })
      .order('created_at', { ascending: false })
      .limit(8),
    admin.from('audit_ledger').select('*', { count: 'exact', head: true }),
    admin
      .from('breaches')
      .select('*', { count: 'exact', head: true })
      .in('status', ['detected', 'triaging', 'contained', 'notifying_dpb', 'notifying_principals']),
    admin
      .from('dsars')
      .select('*', { count: 'exact', head: true })
      .in('status', ['received', 'identity_verification', 'in_fulfilment']),
  ]);

  const tenantCount = tenantsRes.count ?? 0;
  const engagementCount = engagementsRes.count ?? 0;
  const planCount = plansRes.count ?? 0;
  const ledgerCount = ledgerRes.count ?? 0;
  const openBreaches = breachRes.count ?? 0;
  const openDsars = dsarRes.count ?? 0;

  return (
    <div className="flex flex-col gap-8">
      <PageHeader
        title="Agent Workbench"
        description={`The founder's cockpit. Run agents, review outputs, manage prompt versions, and watch the platform's heart beat in real time. ${BRAND.tagline}`}
        meta={
          <>
            <Badge variant="proof">L0 — L1 Autonomy</Badge>
            <Badge variant="indigo">Phase 0 — 1</Badge>
            <Badge variant="neutral">Library v0.1.0</Badge>
          </>
        }
      />

      <StatGrid>
        <Stat label="Active tenants" value={tenantCount} hint="Clients on the platform" />
        <Stat label="Engagements" value={engagementCount} hint="Assessments in flight" />
        <Stat label="Remediation plans" value={planCount} hint="Generated by Sudhaar" />
        <Stat label="Open breaches" value={openBreaches} hint="Need triage" />
        <Stat label="Open DSARs" value={openDsars} hint="Within statutory clock" />
        <Stat label="Ledger entries" value={ledgerCount} hint="Hash-chained & verifiable" />
      </StatGrid>

      <div className="grid grid-cols-1 gap-6 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Recent engagements</CardTitle>
            <CardDescription>Drishti → Vibhaag → Parikshan → Saakshi flow</CardDescription>
          </CardHeader>
          <CardContent>
            {(engagementsRes.data ?? []).length === 0 ? (
              <EmptyState
                title="No engagements yet"
                description="Create an engagement from the client portal to start the discovery → assessment → remediation flow."
              />
            ) : (
              <ul className="flex flex-col gap-2">
                {(engagementsRes.data ?? []).map((e: any) => (
                  <li key={e.id}>
                    <Link
                      href={`/engagements/${e.id}`}
                      className="flex items-center justify-between rounded-md border border-slate-200 px-3 py-2 hover:bg-mist-100"
                    >
                      <div className="flex flex-col">
                        <span className="text-sm font-medium text-slate-700">{e.title}</span>
                        <span className="text-xs text-slate-500">
                          Posture: <span className="font-mono">{e.posture_score ?? '—'}</span>
                        </span>
                      </div>
                      <StatusBadge status={e.status} />
                    </Link>
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Recent plans</CardTitle>
            <CardDescription>Generated by Sudhaar · awaiting or executing</CardDescription>
          </CardHeader>
          <CardContent>
            {(plansRes.data ?? []).length === 0 ? (
              <EmptyState
                title="No plans yet"
                description="Plans are generated after Parikshan completes an assessment."
              />
            ) : (
              <ul className="flex flex-col gap-2">
                {(plansRes.data ?? []).map((p: any) => (
                  <li key={p.id}>
                    <Link
                      href={`/plans/${p.id}`}
                      className="flex items-center justify-between rounded-md border border-slate-200 px-3 py-2 hover:bg-mist-100"
                    >
                      <span className="text-sm font-medium text-slate-700">{p.title}</span>
                      <StatusBadge status={p.status} />
                    </Link>
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>Agent roster</CardTitle>
          <CardDescription>
            10 named agents, each with a contract, an autonomy ceiling, and tool permissions. Per
            Doc 04 §5.2: the planning agent (Sudhaar) holds no write credentials; Karya requires a
            signed approval token to execute.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5">
            {[
              { name: 'drishti' as const, one: "I find what you didn't know you had." },
              { name: 'vibhaag' as const, one: 'I tell you what kind of data it is.' },
              { name: 'parikshan' as const, one: 'I measure you against the law.' },
              { name: 'saakshi' as const, one: 'I am your witness.' },
              { name: 'sudhaar' as const, one: 'I propose the fix. You decide.' },
              { name: 'karya' as const, one: 'I only act on your approval.' },
              { name: 'lekha' as const, one: 'I remember everything, forever.' },
              { name: 'nazar' as const, one: "I watch the law so you don't have to." },
              { name: 'prativedan' as const, one: 'I turn findings into documents.' },
              { name: 'sanket' as const, one: "I find who's about to buy." },
            ].map((a) => (
              <div
                key={a.name}
                className="flex flex-col gap-1.5 rounded-lg border border-slate-200 bg-mist-50 p-3"
              >
                <AgentPill agent={a.name} showPersona={false} />
                <p className="text-xs text-slate-600">{a.one}</p>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function EmptyState({ title, description }: { title: string; description: string }) {
  return (
    <div className="rounded-md border border-dashed border-slate-300 bg-mist-50 p-6 text-center">
      <p className="font-medium text-slate-700">{title}</p>
      <p className="mt-1 text-sm text-slate-500">{description}</p>
    </div>
  );
}
