-- ─────────────────────────────────────────────────────────────────────
-- 0004_remediation_actions.sql
-- Sudhaar's typed remediation plans, the typed action catalogue,
-- the dry-run engine output, and the execution results. This is the
-- core product surface — the action is the atomic unit of the platform.
-- ─────────────────────────────────────────────────────────────────────

create type action_type as enum (
  -- Policy / documentation
  'policy.publish', 'policy.update', 'notice.update', 'consent.update',
  -- Data actions (require rollback plan)
  'data.mask', 'data.delete', 'data.portability_export', 'data.retention_purge',
  -- System configuration
  'config.rbac_update', 'config.mfa_enforce', 'config.backup_encrypt',
  'config.audit_log_enable', 'config.consent_ui_update',
  -- Governance
  'dpo.appoint', 'dpa.execute', 'dpo.contact_publish',
  -- Process
  'breach.playbook_publish', 'training.run', 'review.accept_risk',
  -- Connector-driven (Phase 2+)
  'connector.scan', 'connector.classify',
  -- Catch-all for typed actions not in this list
  'custom'
);

create type action_risk_class as enum ('low', 'medium', 'high', 'critical');

create type plan_status as enum (
  'draft', 'review', 'approved', 'executing', 'completed',
  'partial_failure', 'rolled_back', 'cancelled'
);

create type action_status as enum (
  'draft', 'awaiting_dry_run', 'dry_run_complete', 'awaiting_approval',
  'approved', 'executing', 'succeeded', 'failed', 'rolled_back', 'skipped'
);

-- A remediation plan: collection of typed actions that together address
-- a set of findings.
create table public.remediation_plans (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  engagement_id uuid not null references public.engagements(id) on delete cascade,
  library_version text not null references public.control_libraries(version) on delete restrict,
  title text not null,
  description text,
  status plan_status not null default 'draft',
  -- Plan version (incremented on every change after publish)
  version integer not null default 1,
  -- Optional: dependency to another plan (for chained remediations)
  depends_on uuid references public.remediation_plans(id) on delete set null,
  -- Generated by Sudhaar
  generated_by_agent text not null default 'sudhaar',
  -- Plan-level approval token (covers batch approval)
  plan_approval_token_id uuid,
  -- Aggregate blast radius summary
  aggregate_blast_radius jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_remediation_plans_tenant on public.remediation_plans(tenant_id);
create index idx_remediation_plans_engagement on public.remediation_plans(engagement_id);
create index idx_remediation_plans_status on public.remediation_plans(status);

-- An action — the atomic unit.
-- Important: actions are typed and parameterised (not free-text per ADR/BR).
create table public.remediation_actions (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null references public.tenants(id) on delete cascade,
  plan_id uuid not null references public.remediation_plans(id) on delete cascade,
  -- Order within the plan (1-based)
  sequence integer not null,
  -- Typed action definition
  action_type action_type not null,
  -- Action-specific parameters, validated against the type's parameter schema
  parameters jsonb not null default '{}'::jsonb,
  -- Plain-language description for the approver
  description text not null,
  -- Why this action: which finding(s) does it close
  closes_finding_ids uuid[] not null default '{}',
  -- Risk and blast radius
  risk_class action_risk_class not null default 'medium',
  risk_score numeric(5,2) not null check (risk_score between 0 and 100),
  -- Blast radius: how many records/systems/users would be affected
  blast_radius jsonb not null default '{}'::jsonb,
  -- Mandatory: rollback plan definition (validated as executable before approval)
  rollback_definition jsonb not null,
  -- Rollback validation status
  rollback_validated boolean not null default false,
  rollback_validated_at timestamptz,
  -- Dry-run result (mandatory before approval)
  dry_run_status action_status not null default 'draft',
  dry_run_result jsonb,
  dry_run_completed_at timestamptz,
  dry_run_expires_at timestamptz, -- stale dry-runs cannot back an approval
  -- Approval
  approval_status action_status not null default 'draft',
  approval_token_id uuid,
  approved_by uuid references public.users(id),
  approved_at timestamptz,
  -- Execution
  execution_status action_status not null default 'draft',
  executed_by_agent text, -- 'karya'
  executed_at timestamptz,
  -- Pre / post state references (S3)
  pre_state_uri text,
  post_state_uri text,
  -- Verification (after execution)
  verification_status action_status,
  verification_result jsonb,
  verified_at timestamptz,
  -- Outcome: succeeded | failed | rolled_back | skipped
  final_outcome text check (final_outcome in ('succeeded', 'failed', 'rolled_back', 'skipped')),
  -- Idempotency key from the API
  idempotency_key text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_remediation_actions_tenant on public.remediation_actions(tenant_id);
create index idx_remediation_actions_plan on public.remediation_actions(plan_id);
create index idx_remediation_actions_status on public.remediation_actions(approval_status);
create index idx_remediation_actions_exec_status on public.remediation_actions(execution_status);
create index idx_remediation_actions_idem on public.remediation_actions(idempotency_key);

-- RLS
alter table public.remediation_plans enable row level security;
alter table public.remediation_actions enable row level security;

-- Plans: tenant members see their plans; Axiom internal sees all
create policy "plans_select_member" on public.remediation_plans
  for select using (
    public.is_tenant_member(tenant_id)
    or exists (select 1 from public.users where id = auth.uid() and is_axiom_internal)
  );

create policy "plans_insert_reviewer_or_axiom" on public.remediation_plans
  for insert with check (
    public.has_role(array['owner', 'admin', 'reviewer', 'agent']::user_role[])
    or exists (select 1 from public.users where id = auth.uid() and is_axiom_internal)
  );

create policy "plans_update_reviewer_or_axiom" on public.remediation_plans
  for update using (
    public.has_role(array['owner', 'admin', 'reviewer', 'approver', 'agent']::user_role[])
    or exists (select 1 from public.users where id = auth.uid() and is_axiom_internal)
  );

-- Actions: same as plans, but updates are heavily constrained by triggers
create policy "actions_select_member" on public.remediation_actions
  for select using (
    public.is_tenant_member(tenant_id)
    or exists (select 1 from public.users where id = auth.uid() and is_axiom_internal)
  );

create policy "actions_insert_reviewer_or_axiom" on public.remediation_actions
  for insert with check (
    public.has_role(array['owner', 'admin', 'reviewer', 'agent']::user_role[])
    or exists (select 1 from public.users where id = auth.uid() and is_axiom_internal)
  );

create policy "actions_update_reviewer_or_axiom" on public.remediation_actions
  for update using (
    public.has_role(array['owner', 'admin', 'reviewer', 'approver', 'agent']::user_role[])
    or exists (select 1 from public.users where id = auth.uid() and is_axiom_internal)
  );

-- Action immutability: once an action is approved, its core definition
-- (action_type, parameters, rollback_definition, closes_finding_ids) is
-- locked. The only fields that can change are the status fields.
create or replace function public.actions_approved_immutable()
returns trigger language plpgsql as $$
begin
  if old.approval_status in ('approved', 'executing', 'succeeded') then
    if new.action_type is distinct from old.action_type then
      raise exception 'action_type is immutable once approved';
    end if;
    if new.parameters is distinct from old.parameters then
      raise exception 'parameters are immutable once approved';
    end if;
    if new.rollback_definition is distinct from old.rollback_definition then
      raise exception 'rollback_definition is immutable once approved';
    end if;
    if new.closes_finding_ids is distinct from old.closes_finding_ids then
      raise exception 'closes_finding_ids is immutable once approved';
    end if;
  end if;
  return new;
end;
$$;

create trigger trg_actions_approved_immutable
  before update on public.remediation_actions
  for each row execute function public.actions_approved_immutable();
