import Link from 'next/link';
import { createSupabaseAdmin } from '@axiom/supabase';
import { redirect } from 'next/navigation';
import {
  PageHeader,
  Card,
  CardHeader,
  CardTitle,
  CardContent,
  StatusBadge,
  Badge,
} from '@axiom/ui';
import { formatDate, formatPercent } from '@axiom/ui';
import { createSupabaseServerClient } from '@axiom/supabase';

export const dynamic = 'force-dynamic';

export default async function PlansListPage() {
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect('/login');

  const admin = createSupabaseAdmin();
  const { data: plans } = await admin
    .from('remediation_plans')
    .select('id, title, status, version, created_at, tenant_id, engagement_id, library_version')
    .order('created_at', { ascending: false });

  const pending = (plans ?? []).filter((p: any) =>
    ['draft', 'review', 'approved', 'executing'].includes(p.status),
  );
  const closed = (plans ?? []).filter((p: any) =>
    ['completed', 'rolled_back', 'cancelled', 'partial_failure'].includes(p.status),
  );

  return (
    <div className="flex flex-col gap-6">
      <PageHeader
        title="Remediation plans"
        description="Generated by Sudhaar from Parikshan findings. Every action requires a dry-run, a rollback plan, and a human approval before execution."
        meta={<Badge variant="indigo">{(plans ?? []).length} total</Badge>}
      />

      <Card>
        <CardHeader>
          <CardTitle>Active</CardTitle>
        </CardHeader>
        <CardContent>
          {pending.length === 0 ? (
            <p className="text-sm text-slate-500">No active plans.</p>
          ) : (
            <PlansTable plans={pending} />
          )}
        </CardContent>
      </Card>

      {closed.length > 0 && (
        <Card>
          <CardHeader>
            <CardTitle>Closed</CardTitle>
          </CardHeader>
          <CardContent>
            <PlansTable plans={closed} />
          </CardContent>
        </Card>
      )}
    </div>
  );
}

function PlansTable({ plans }: { plans: any[] }) {
  return (
    <div className="overflow-hidden rounded-md border border-slate-200">
      <table className="w-full text-sm">
        <thead className="bg-mist-50 text-left text-xs uppercase tracking-wider text-slate-500">
          <tr>
            <th className="px-4 py-2">Title</th>
            <th className="px-4 py-2">Status</th>
            <th className="px-4 py-2">Version</th>
            <th className="px-4 py-2">Library</th>
            <th className="px-4 py-2">Created</th>
            <th className="px-4 py-2" />
          </tr>
        </thead>
        <tbody className="divide-y divide-slate-200">
          {plans.map((p) => (
            <tr key={p.id} className="hover:bg-mist-50">
              <td className="px-4 py-2 font-medium text-slate-700">{p.title}</td>
              <td className="px-4 py-2">
                <StatusBadge status={p.status} />
              </td>
              <td className="px-4 py-2 font-mono text-xs text-slate-500">v{p.version}</td>
              <td className="px-4 py-2 font-mono text-xs text-slate-500">{p.library_version}</td>
              <td className="px-4 py-2 text-xs text-slate-500">{formatDate(p.created_at)}</td>
              <td className="px-4 py-2 text-right">
                <Link
                  href={`/plans/${p.id}`}
                  className="rounded-md border border-slate-300 px-3 py-1 text-xs hover:bg-mist-100"
                >
                  Open
                </Link>
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
