"""Prativedan — the Reporting Agent.

"I turn findings into documents."

Prativedan generates Board reports, auditor packs, and DPB-ready
submissions. Every claim in a report is traceable to a specific
evidence artifact. The founder reviews and signs off before any
report reaches a client.

In Phase 0, Prativedan produces structured JSON + an HTML/PDF
rendering. The agent references the control library + findings
data and uses the model gateway to draft the prose.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, ClassVar

from pydantic import BaseModel, Field


class ReportKind(str, Enum):
    BOARD = "board"
    AUDITOR = "auditor"
    DPB = "dpb"
    TECHNICAL = "technical"
    GAP_SCAN = "gap_scan"
    EVIDENCE_PACK = "evidence_pack"
    CUSTOM = "custom"


from .base import AgentName, AutonomyLevel, BaseAgent
from ..model_gateway import ModelRequest, TaskKind


class PrativedanInput(BaseModel):
    tenant_id: str
    engagement_id: str | None = None
    kind: ReportKind = ReportKind.BOARD
    title: str
    findings: list[dict[str, Any]] = Field(default_factory=list)
    posture_score: float | None = None
    estimated_exposure_inr: int | None = None
    library_version: str = "0.1.0"
    reviewer_id: str | None = None


class PrativedanOutput(BaseModel):
    title: str
    kind: str
    sections: list[dict[str, Any]]
    cited_evidence_ids: list[str] = Field(default_factory=list)
    generated_by_agent: str = "prativedan"
    rendered_html: str = ""


class PrativedanAgent(BaseAgent[PrativedanInput, PrativedanOutput]):
    name: ClassVar[AgentName] = AgentName.PRATIVEDAN
    description: ClassVar[str] = "Generate a structured compliance report from findings."
    one_liner: ClassVar[str] = "I turn findings into documents."
    tool_scopes: ClassVar[tuple[str, ...]] = ("report.write", "pdf.render")
    autonomy: ClassVar[AutonomyLevel] = AutonomyLevel.L1
    default_task_kind: ClassVar[Any] = "report"
    default_pii_redact: ClassVar[bool] = True

    def input_schema(self) -> type[PrativedanInput]:
        return PrativedanInput

    def output_schema(self) -> type[PrativedanOutput]:
        return PrativedanOutput

    async def _run(
        self, *, correlation_id: str, input: PrativedanInput, **deps: Any
    ) -> PrativedanOutput:
        # Section: executive summary
        posture = input.posture_score or 0
        verdict = (
            "Strong" if posture >= 85
            else "Acceptable" if posture >= 65
            else "At Risk" if posture >= 40
            else "Critical"
        )
        executive_summary = {
            "type": "executive_summary",
            "title": "Executive summary",
            "body": (
                f"Posture score: {posture:.0f}/100 ({verdict}). "
                f"Estimated max statutory exposure: ₹{(input.estimated_exposure_inr or 0) / 1e7:.2f} Cr. "
                f"{len(input.findings)} findings reviewed. "
                f"Library version: {input.library_version}."
            ),
        }

        # Section: top findings (top 10 by risk_points)
        top = sorted(input.findings, key=lambda f: f.get("risk_points", 0), reverse=True)[:10]
        top_section = {
            "type": "findings_table",
            "title": "Top findings (by risk-weighted exposure)",
            "items": [
                {
                    "control_id": f.get("control_id"),
                    "title": f.get("title"),
                    "severity": f.get("severity"),
                    "score": f.get("score"),
                    "risk_points": f.get("risk_points"),
                    "rationale": f.get("rationale"),
                }
                for f in top
            ],
        }

        # Section: control library reference
        library_section = {
            "type": "library",
            "title": "Control library",
            "body": f"Scored against the Axiom Proof Control Library v{input.library_version} (46 controls).",
        }

        # Section: agent attribution + human reviewer
        attribution = {
            "type": "attribution",
            "title": "Generated and reviewed by",
            "body": (
                f"Generated by Prativedan (v{self.version}). "
                + (f"Reviewed by {input.reviewer_id}." if input.reviewer_id else "Pending review.")
            ),
        }

        sections = [executive_summary, top_section, library_section, attribution]

        # Render HTML
        rendered = self._render_html(input.title, sections, posture, verdict)

        return PrativedanOutput(
            title=input.title,
            kind=input.kind.value if isinstance(input.kind, ReportKind) else str(input.kind),
            sections=sections,
            cited_evidence_ids=[
                eid
                for f in input.findings
                for eid in f.get("evidence_required", [])
                if isinstance(eid, str)
            ],
            rendered_html=rendered,
        )

    def _render_html(
        self, title: str, sections: list[dict[str, Any]], posture: float, verdict: str
    ) -> str:
        out = [f"<h1>{title}</h1>"]
        out.append(
            f'<div class="axiom-cover"><p>Posture: <strong>{posture:.0f}/100 ({verdict})</strong></p></div>'
        )
        for s in sections:
            out.append(f"<h2>{s.get('title', '')}</h2>")
            if s.get("body"):
                out.append(f"<p>{s['body']}</p>")
            if s.get("type") == "findings_table" and s.get("items"):
                rows = "".join(
                    f"<tr><td>{i.get('control_id')}</td><td>{i.get('title')}</td>"
                    f"<td>{i.get('severity')}</td><td>{i.get('score')}</td>"
                    f"<td>{i.get('risk_points')}</td></tr>"
                    for i in s["items"]
                )
                out.append(
                    "<table><thead><tr><th>Control</th><th>Title</th><th>Severity</th>"
                    "<th>Score</th><th>Risk pts</th></tr></thead>"
                    f"<tbody>{rows}</tbody></table>"
                )
        return "\n".join(out)
