apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "axiom-proof.serviceAccountName" . }}
  labels:
    {{- include "axiom-proof.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
